"""`retrosync wrap-*` subcommand backends.

The Steam launch shortcuts (generated by Steam ROM Manager, patched by
`deck.srm`) invoke a small bash dispatcher (installed at
`~/.local/bin/retrosync-wrap`) that:

  1. Calls `retrosync wrap-extract-rom` to find the ROM path inside the
     emulator command line.
  2. Calls `retrosync wrap-derive-game-id` to canonicalize ROM-stem →
     `(system, game_id)`.
  3. Calls `retrosync wrap-pre` to do the pre-launch sync + lease grab.
  4. exec's the emulator.
  5. After exit, calls `retrosync wrap-post` to release the lease and
     flush any in-flight uploads.

Splitting into four small Python subcommands keeps the bash dispatcher
trivial (no Python startup-cost during exec) and lets us unit-test each
piece in isolation.

In the spec, "wrap" is the umbrella command operators see; in the code
the verbs are the four wrap-* subcommands the bash script calls.
"""
from __future__ import annotations

import asyncio
import logging
import sys
from dataclasses import dataclass
from pathlib import Path

from .. import leases as leases_mod
from ..cloud import CloudError, RcloneCloud, compose_paths
from ..config import Config
from ..game_id import resolve_game_id
from ..lease_tracker import LeaseTracker
from ..sources.base import SaveRef
from ..sources.registry import build as build_source
from ..state import StateStore
from ..sync import (SyncConfig, SyncContext, sync_one_game)

log = logging.getLogger(__name__)


# Common ROM extensions the wrap dispatcher recognizes when sniffing
# the emulator command line for a ROM argument.
ROM_EXTENSIONS = (
    ".sfc", ".smc", ".swc", ".fig",
    ".gb", ".gbc", ".gba",
    ".nes", ".unf", ".unif",
    ".md", ".gen", ".smd",
    ".z64", ".n64", ".v64",
    ".pce", ".tg16",
    ".cue", ".chd", ".iso",
)


@dataclass
class DerivedGame:
    rom_path: Path
    system: str
    game_id: str


def extract_rom_from_args(args: list[str], *,
                          rom_extensions: tuple[str, ...] = ROM_EXTENSIONS,
                          ) -> Path | None:
    """Walk emulator-command args; return the first thing that looks
    like a ROM path on disk.

    Heuristic: argument matches a known ROM extension AND the path
    exists. Order matters — RetroArch-style commands have the ROM as
    the last positional arg, but standalones may put options after.
    """
    for arg in args:
        if not arg or arg.startswith("-"):
            continue
        if not arg.lower().endswith(rom_extensions):
            continue
        p = Path(arg)
        if p.exists():
            return p
    return None


def derive_from_rom(rom_path: Path, *,
                    emudeck_root: Path | None = None,
                    aliases: dict[str, list[str]] | None = None,
                    ) -> DerivedGame | None:
    """Map a ROM path → (system, game_id).

    The system comes from the ROM's parent directory name relative to
    `<emudeck_root>/roms/`. If `emudeck_root` is given and the ROM is
    under it, the system is the path component immediately after `roms/`.
    Otherwise, fall back to the ROM's parent dir name.
    """
    if not rom_path.exists():
        return None
    system: str | None = None
    if emudeck_root is not None:
        try:
            rel = rom_path.relative_to(emudeck_root / "roms")
            parts = rel.parts
            if len(parts) >= 2:
                system = parts[0]
        except ValueError:
            system = None
    if system is None:
        system = rom_path.parent.name
    game_id = resolve_game_id(rom_path.name, aliases=aliases)
    return DerivedGame(rom_path=rom_path, system=system, game_id=game_id)


# --------------------------------------------------------------------------
# Subcommand entrypoints. Each returns the exit code.
# --------------------------------------------------------------------------

def cmd_extract_rom(args: list[str]) -> int:
    """`retrosync wrap-extract-rom -- <emulator-args>` — print the ROM path."""
    if "--" in args:
        args = args[args.index("--") + 1:]
    rom = extract_rom_from_args(args)
    if rom is None:
        return 1
    sys.stdout.write(str(rom))
    sys.stdout.write("\n")
    return 0


def cmd_derive_game_id(rom_path_str: str, *,
                       config: Config) -> int:
    """`retrosync wrap-derive-game-id <rom-path>` — print
    `<system>:<game_id>` so the bash dispatcher can capture it."""
    rom_path = Path(rom_path_str)
    if not rom_path.exists():
        log.error("derive_game_id: %s does not exist", rom_path)
        return 1
    derived = derive_from_rom(rom_path, aliases=config.game_aliases)
    if derived is None:
        return 1
    sys.stdout.write(f"{derived.system}:{derived.game_id}\n")
    return 0


def resolve_source_id(*, source_id: str, system: str,
                      config: Config) -> str:
    """Pick the right source_id for `system`.

    The wrap dispatcher passes a single SOURCE_ID env var (default
    `deck-1`, which predates multi-system support). With multi-system
    configs (`deck-1-snes`, `deck-1-n64`, ...) the dispatcher's
    hardcoded value is wrong for any system except the one it was
    set for. Auto-correct by:

      1. If `source_id` exists AND its emudeck system matches, use it.
      2. Otherwise find the first emudeck source whose
         `options.system` matches `system` and use that.
      3. If no source matches, return `source_id` unchanged — the
         caller will see "no source in config" and skip the sync,
         which is the right "fail open" behavior for the wrap path.
    """
    by_id = {s.id: s for s in config.sources}
    s = by_id.get(source_id)
    if s is not None and s.adapter == "emudeck" \
            and s.options.get("system") == system:
        return source_id
    for cand in config.sources:
        if cand.adapter == "emudeck" \
                and cand.options.get("system") == system:
            log.info("wrap: source_id %r doesn't fit system %r; "
                     "using %r instead", source_id, system, cand.id)
            return cand.id
    log.warning("wrap: no emudeck source configured for system %r; "
                "lease/sync will be skipped", system)
    return source_id


def cmd_wrap_pre(*, source_id: str, system: str, game_id: str,
                 config: Config, timeout_sec: float = 10.0) -> int:
    """Pre-launch sync + lease grab for one game.

    Runs sync_one_game (cloud → device if cloud is ahead), then grabs
    the lease so other devices know we're playing. On any failure,
    LOGS the error and returns 0 — never block the operator's launch.
    Worst case: emulator launches with a slightly-stale local save,
    which the next inotify-driven push will reconcile.
    """
    return asyncio.run(_async_wrap_pre(
        source_id=source_id, system=system, game_id=game_id,
        config=config, timeout_sec=timeout_sec))


async def _async_wrap_pre(*, source_id: str, system: str, game_id: str,
                          config: Config, timeout_sec: float) -> int:
    source_id = resolve_source_id(source_id=source_id, system=system,
                                  config=config)
    state = StateStore(config.state.db_path)
    try:
        cloud = RcloneCloud(remote=config.cloud.rclone_remote,
                            binary=config.cloud.rclone_binary,
                            config_path=config.cloud.rclone_config_path)
        # Build the source — the wrap path needs an EmuDeckSource so the
        # sync engine can read/write the device save in the same way the
        # daemon does.
        src_cfg = next((s for s in config.sources if s.id == source_id),
                       None)
        if src_cfg is None:
            log.warning("wrap_pre: no source %r in config; running "
                        "lease-only", source_id)
            source = None
        else:
            source = build_source(src_cfg.adapter, id=src_cfg.id,
                                  **src_cfg.options)
        # Compose paths from a placeholder filename — the engine doesn't
        # need the local filename to read the cloud manifest. The actual
        # save filename is resolved per-source on the write path.
        paths = compose_paths(remote=cloud.remote, system=system,
                              game_id=game_id,
                              save_filename=f"{game_id}.bin")
        # Best-effort sync. If it times out, we still launch.
        if source is not None:
            sync_cfg = SyncConfig(
                cloud_to_device=config.cloud_to_device,
                conflict_winner=config.conflict_winner,
                cloud_wins_on_unknown_device=config.cloud_wins_on_unknown_device,
                cloud_wins_on_diverged_device=config.cloud_wins_on_diverged_device,
                drift_threshold=dict(config.drift_threshold))
            ctx = SyncContext(state=state, cloud=cloud, cfg=sync_cfg)
            try:
                await asyncio.wait_for(_sync_for_game(
                    source=source, source_id=source_id, system=system,
                    game_id=game_id, ctx=ctx),
                    timeout=timeout_sec)
            except asyncio.TimeoutError:
                log.warning("wrap_pre: sync of %s timed out after %.1fs; "
                            "launching with stale local", game_id,
                            timeout_sec)
            except (CloudError, Exception) as exc:  # noqa: BLE001
                log.warning("wrap_pre: sync of %s failed: %s; "
                            "launching anyway", game_id, exc)
        # Lease grab. In hard-mode contention, log + still launch — the
        # design says even hard mode "exits non-zero, preventing the
        # emulator from launching", but the bash trap honors that
        # already (we exit 1 here and the dispatcher checks). We do let
        # soft mode override.
        try:
            outcome = leases_mod.acquire(
                cloud=cloud, paths=paths,
                source_id=source_id, mode=config.lease.mode,
                ttl_minutes=config.lease.ttl_minutes)
        except leases_mod.LeaseContended as exc:
            sys.stderr.write(
                f"[retrosync] hard-mode lease contention for {game_id}: "
                f"held by {exc.lease.source_id} until {exc.lease.expires_at}. "
                "Wait for them to finish, or run:\n"
                f"  retrosync lease release {source_id}:{game_id} --force\n")
            return 1
        except CloudError as exc:
            log.warning("wrap_pre: lease acquire failed: %s; proceeding",
                        exc)
            return 0
        if outcome.contended and outcome.prior is not None:
            sys.stderr.write(
                f"[retrosync] heads up: {outcome.prior.source_id} was "
                f"active for {game_id} (last heartbeat "
                f"{outcome.prior.last_heartbeat}). Pulled latest cloud "
                "and continuing.\n")
        return 0
    finally:
        state.close()


async def _sync_for_game(*, source, source_id: str, system: str,
                         game_id: str, ctx: SyncContext) -> None:
    """Discover the device-side save for `game_id` and run sync_one_game.

    Walks `source.list_saves()`, picks the ref whose game_id matches.
    If none exists yet, builds a synthetic ref pointing at the
    filename_for(game_id) target — sync_one_game will detect that as a
    bootstrap-pull case (h_dev = None).
    """
    refs = await source.list_saves()
    target_ref = None
    for ref in refs:
        if source.resolve_game_id(ref) == game_id:
            target_ref = ref
            break
    if target_ref is None:
        # Bootstrap. Synthesize a ref pointing at where we'd write.
        filename = source.filename_for(state=ctx.state, game_id=game_id)
        if filename is None:
            log.info("wrap_pre: no on-device save and no matching ROM "
                     "for %s — nothing to pull", game_id)
            return
        target_ref = SaveRef(path=str(source.saves_root / filename))
    await sync_one_game(source=source, ref=target_ref, ctx=ctx)


def cmd_wrap_post(*, source_id: str, system: str, game_id: str,
                  config: Config, timeout_sec: float = 30.0) -> int:
    """Post-exit: release the lease, flush in-flight uploads, exit.

    Runs even if the emulator crashed (it's the bash trap). Errors
    are logged but never raised — the user's already done playing,
    nothing useful to surface."""
    return asyncio.run(_async_wrap_post(
        source_id=source_id, system=system, game_id=game_id,
        config=config, timeout_sec=timeout_sec))


async def _async_wrap_post(*, source_id: str, system: str, game_id: str,
                           config: Config, timeout_sec: float) -> int:
    source_id = resolve_source_id(source_id=source_id, system=system,
                                  config=config)
    state = StateStore(config.state.db_path)
    try:
        cloud = RcloneCloud(remote=config.cloud.rclone_remote,
                            binary=config.cloud.rclone_binary,
                            config_path=config.cloud.rclone_config_path)
        # Last sync pass for this game so any saved-just-before-quit
        # bytes get to cloud before we drop the lease.
        src_cfg = next((s for s in config.sources if s.id == source_id),
                       None)
        if src_cfg is not None:
            try:
                source = build_source(src_cfg.adapter, id=src_cfg.id,
                                      **src_cfg.options)
                sync_cfg = SyncConfig(
                    cloud_to_device=config.cloud_to_device,
                    conflict_winner=config.conflict_winner,
                    cloud_wins_on_unknown_device=config.cloud_wins_on_unknown_device,
            cloud_wins_on_diverged_device=config.cloud_wins_on_diverged_device,
                    drift_threshold=dict(config.drift_threshold))
                ctx = SyncContext(state=state, cloud=cloud, cfg=sync_cfg)
                await asyncio.wait_for(_sync_for_game(
                    source=source, source_id=source_id, system=system,
                    game_id=game_id, ctx=ctx),
                    timeout=timeout_sec)
            except asyncio.TimeoutError:
                log.warning("wrap_post: sync of %s timed out", game_id)
            except Exception as exc:  # noqa: BLE001
                log.warning("wrap_post: sync of %s failed: %s",
                            game_id, exc)
        paths = compose_paths(remote=cloud.remote, system=system,
                              game_id=game_id,
                              save_filename=f"{game_id}.bin")
        try:
            leases_mod.release(cloud=cloud, paths=paths,
                               source_id=source_id)
        except CloudError as exc:
            log.warning("wrap_post: lease release failed: %s "
                        "(will expire on its own at TTL)", exc)
        return 0
    finally:
        state.close()
